"use client";
import { FormEvent, useEffect, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "@/lib/supabase/client";
import MetaConnect from "./meta-connect";
import { WorkspaceOverview, MediaPicker } from "./workspace-panels";
import { Sparkles, LayoutDashboard, FolderOpen, UploadCloud, Building2, Link2, LogOut, RefreshCw, Plus } from "lucide-react";

type Brand={id:string;name:string;niche:string|null};
type Content={id:string;brand_id:string;title:string;status:string;media_type:string;created_at:string};
type Job={id:string;content_item_id:string;platform:string;publish_kind:string;scheduled_for:string;status:string;error_message:string|null};

export default function Page(){
 const [session,setSession]=useState<Session|null>(null),[ready,setReady]=useState(false),[busy,setBusy]=useState(false);
 const [brands,setBrands]=useState<Brand[]>([]),[content,setContent]=useState<Content[]>([]),[jobs,setJobs]=useState<Job[]>([]),[msg,setMsg]=useState("");
 const [uploadVersion,setUploadVersion]=useState(0);
 const [tab,setTab]=useState<"dashboard"|"content"|"upload"|"brands"|"meta">("dashboard");
 useEffect(()=>{if(new URLSearchParams(window.location.search).get("tab")==="meta")setTab("meta");supabase.auth.getSession().then(x=>{setSession(x.data.session);setReady(true)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)void load()},[session]);
 async function load(){setBusy(true);const boot=await supabase.rpc("bootstrap_workspace",{org_name:"MediaGrow"});if(boot.error){setMsg(boot.error.message);setBusy(false);return}const [b,c,j]=await Promise.all([supabase.from("brands").select("id,name,niche").order("created_at"),supabase.from("content_items").select("id,brand_id,title,status,media_type,created_at").order("created_at",{ascending:false}).limit(100),supabase.from("publish_jobs").select("id,content_item_id,platform,publish_kind,scheduled_for,status,error_message").order("scheduled_for",{ascending:false}).limit(200)]);setBrands((b.data||[]) as Brand[]);setContent((c.data||[]) as Content[]);setJobs((j.data||[]) as Job[]);if(b.error||c.error||j.error)setMsg(b.error?.message||c.error?.message||j.error?.message||"");setBusy(false)}
 if(!ready)return <main className="center">Loading…</main>;
 if(!session)return <Auth/>;
 const userId=session.user.id;
 async function addBrand(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget;setBusy(true);setMsg("");const f=new FormData(form);const r=await supabase.rpc("create_brand",{p_name:String(f.get("name")),p_niche:String(f.get("niche")||"")||null,p_timezone:"Asia/Jakarta"});setBusy(false);setMsg(r.error?.message||"Brand dibuat");if(!r.error){form.reset();await load()}}
 async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget;const f=new FormData(form),file=f.get("file") as File,brand=String(f.get("brand")),title=String(f.get("title"));if(!file?.size)return;const selected=["ig_feed","ig_story","ig_reel","fb_feed","fb_story","fb_reel"].filter(x=>f.get(x)==="on");if(!selected.length){setMsg("Pilih setidaknya satu channel tujuan.");return}if(file.type.startsWith("image/")&&selected.some(x=>x.endsWith("reel"))){setMsg("Reel membutuhkan video. Gunakan Feed atau Story untuk gambar.");return}setBusy(true);setMsg("");const media=file.type.startsWith("video/")?"video":"image",path=`${brand}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const up=await supabase.storage.from("content-media").upload(path,file,{contentType:file.type,upsert:false});if(up.error){setBusy(false);setMsg(up.error.message);return}const row=await supabase.from("content_items").insert({brand_id:brand,created_by:userId,title,brief:String(f.get("brief")||"")||null,caption:String(f.get("caption")||"")||null,media_type:media,primary_asset_path:path,status:"ready",auto_schedule:true}).select("id").single();if(row.error||!row.data){await supabase.storage.from("content-media").remove([path]);setBusy(false);setMsg(row.error?.message||"Gagal membuat konten");return}const channels=["ig_feed","ig_story","ig_reel","fb_feed","fb_story","fb_reel"].filter(x=>f.get(x)==="on");const sch=await supabase.rpc("schedule_content",{p_content_id:row.data.id,p_channels:channels,p_scheduled_for:null});setBusy(false);setMsg(sch.error?`Konten tersimpan, jadwal belum dibuat: ${sch.error.message}`:"Upload + auto-schedule berhasil");form.reset();setUploadVersion(v=>v+1);await load()}
 const brandName=(id:string)=>brands.find(b=>b.id===id)?.name||"Brand";
 const nav=[{id:"dashboard",label:"Ringkasan",icon:LayoutDashboard},{id:"content",label:"Pustaka konten",icon:FolderOpen},{id:"upload",label:"Upload konten",icon:UploadCloud},{id:"brands",label:"Brand",icon:Building2},{id:"meta",label:"Koneksi akun",icon:Link2}] as const;
 return <div className="shell"><aside className="sidebar"><a href="/" className="brand-lockup"><span className="brand-mark"><Sparkles size={22}/></span><span>MediaGrow<small>CONTENT HUB</small></span></a><p className="nav-heading">RUANG KERJA</p><nav aria-label="Navigasi utama">{nav.map(n=><button className={tab===n.id?"active":""} aria-current={tab===n.id?"page":undefined} key={n.id} onClick={()=>{setTab(n.id);setMsg("")}}><n.icon size={19}/><span>{n.label}</span></button>)}</nav><div className="sidebar-bottom"><div className="workspace-label"><b>Workspace MediaGrow</b><small>Instagram & Facebook</small></div><button className="logout" onClick={()=>void supabase.auth.signOut()}><LogOut size={17}/>Keluar</button></div></aside><main className="workspace"><header className="topbar"><div><small>WORKSPACE / MEDIAGROW</small><h2>{nav.find(n=>n.id===tab)?.label}</h2></div><div className="topbar-actions"><span className="timezone">WIB · Asia/Jakarta</span><button className="secondary" onClick={()=>{setMsg("");void load()}} disabled={busy}><RefreshCw size={16} className={busy?"spinning":""}/><span>Perbarui</span></button></div></header><section className="page-heading"><div><span className="eyebrow">MEDIA GROW, TOGETHER</span><h1>{tab==="dashboard"?"Ruang kerja kontenmu":tab==="content"?"Semua ide, satu pustaka":tab==="upload"?"Siapkan konten berikutnya":tab==="brands"?"Brand yang kamu kelola":"Terhubung, siap berkarya"}</h1><p>{tab==="dashboard"?"Pantau publikasi setiap brand dalam satu tempat.":tab==="upload"?"Dari bahan kreatif menjadi publikasi yang terjadwal.":"Kelola bahan dan akun tujuan bersama timmu."}</p></div>{tab!=="upload"&&<button className="primary" onClick={()=>{setTab("upload");setMsg("")}}><Plus size={18}/>Upload konten</button>}</section>{msg&&<div className="notice" role="status">{msg}</div>}

 {(tab==="dashboard"||tab==="content")&&<WorkspaceOverview key={tab} brands={brands} content={content} jobs={jobs} library={tab==="content"} onUpload={()=>{setTab("upload");setMsg("")}}/>}
 {tab==="brands"&&<section className="card narrow"><div className="section-heading"><div><h3>Tambah brand</h3><p>Setiap brand memiliki konten dan koneksi akun sendiri.</p></div><Building2 size={23}/></div><form onSubmit={addBrand}><label>Nama brand<input name="name" placeholder="Contoh: Gudang WPC" required/></label><label>Kategori / niche<input name="niche" placeholder="Interior, F&B, Fashion..."/></label><button disabled={busy}>Simpan Brand</button></form><div className="brand-grid">{brands.map(b=><article className="brand-tile" key={b.id}><span className="brand-initial">{b.name.slice(0,2).toUpperCase()}</span><h4>{b.name}</h4><p>{b.niche||"Belum ada kategori"}</p></article>)}</div></section>}
 {tab==="meta"&&<MetaConnect brands={brands} userId={userId} onConnected={()=>void load()}/>}
 {tab==="upload"&&<section className="card narrow upload-card"><div className="section-heading"><div><h3>Upload & jadwalkan</h3><p>Lengkapi bahan, caption, dan channel tujuan publikasi.</p></div><UploadCloud size={24}/></div><form onSubmit={upload}><label>Brand<select name="brand" required><option value="">Pilih</option>{brands.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label><label>Judul<input name="title" required/></label><MediaPicker key={uploadVersion}/><label>Caption<textarea name="caption" placeholder="Tulis cerita, ajakan bertindak, dan hashtag brand…" rows={5}/></label><label>Brief untuk tim · opsional<textarea name="brief" placeholder="Catatan tentang konsep atau bahan konten" rows={2}/></label><fieldset><legend>Channel publikasi</legend>{["ig_feed","ig_story","ig_reel","fb_feed","fb_story","fb_reel"].map(x=><label className="check" key={x}><input type="checkbox" name={x} defaultChecked={["ig_feed","ig_story","fb_feed"].includes(x)}/>{x.replace("ig_","Instagram ").replace("fb_","Facebook ")}</label>)}</fieldset><p className="inline-help">Pastikan akun tujuan sudah terhubung. Jadwal dibuat otomatis dan dipublikasikan ketika waktunya tiba.</p><button disabled={busy||!brands.length}>{busy?"Memproses…":"Upload & jadwalkan"}</button></form></section>}
 </main></div>}

function Auth(){const [signup,setSignup]=useState(false),[msg,setMsg]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),email=String(f.get("email")),password=String(f.get("password"));const r=signup?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});if(r.error)setMsg(r.error.message);else if(signup&&!r.data.session)setMsg("Cek email untuk konfirmasi akun.")}return <main className="auth"><form onSubmit={submit}><div className="auth-brand"><span className="brand-mark"><Sparkles size={24}/></span><span>MediaGrow<small>CONTENT HUB</small></span></div><span className="eyebrow">RUANG KERJA TIM KONTEN</span><h1>{signup?"Buat akun tim":"Selamat datang kembali"}</h1><p>Kelola banyak brand. Siapkan konten. Publikasikan sesuai jadwal.</p><label>Email<input name="email" type="email" autoComplete="email" placeholder="nama@bisnismu.com" required/></label><label>Password<input name="password" type="password" autoComplete={signup?"new-password":"current-password"} placeholder="Masukkan password" minLength={6} required/></label>{msg&&<div className="notice">{msg}</div>}<button>{signup?"Daftar":"Masuk"}</button><button type="button" className="link" onClick={()=>setSignup(!signup)}>{signup?"Sudah punya akun":"Buat akun tim"}</button></form></main>}
