"use client";
import { useEffect, useState } from "react";
import { ArrowUpRight, Building2, CalendarDays, CheckCircle2, Clock3, FileImage, FolderOpen, Search, UploadCloud, Video } from "lucide-react";

type Brand = { id: string; name: string; niche: string | null };
type Content = { id: string; brand_id: string; title: string; status: string; media_type: string; created_at: string };
type Job = { id: string; content_item_id: string; platform: string; publish_kind: string; scheduled_for: string; status: string; error_message: string | null };
const names: Record<string, string> = { ready: "Siap", draft: "Draf", scheduled: "Terjadwal", retrying: "Dicoba ulang", publishing: "Dipublikasikan…", posted: "Terbit", failed: "Gagal", cancelled: "Dibatalkan", archived: "Diarsipkan" };
const date = (v: string) => new Date(v).toLocaleString("id-ID", { timeZone: "Asia/Jakarta", day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" });
const active = (j: Job) => ["scheduled", "retrying", "publishing"].includes(j.status);
function Badge({ status }: { status: string }) { return <span className={`status ${status}`}><i/>{names[status] || status}</span>; }

export function WorkspaceOverview({ brands, content, jobs, library = false, onUpload }: { brands: Brand[]; content: Content[]; jobs: Job[]; library?: boolean; onUpload: () => void }) {
  const [query, setQuery] = useState(""), [brand, setBrand] = useState(""), [status, setStatus] = useState("");
  const contentMap = new Map(content.map(c => [c.id, c]));
  const brandName = (id?: string) => brands.find(b => b.id === id)?.name || "—";
  const scope = jobs.filter(j => !brand || contentMap.get(j.content_item_id)?.brand_id === brand);
  const listed = scope.filter(j => (!status || (status === "active" ? active(j) : j.status === status)) && (contentMap.get(j.content_item_id)?.title || j.content_item_id).toLowerCase().includes(query.toLowerCase())).sort((a, b) => Number(active(b)) - Number(active(a)) || (active(a) ? Date.parse(a.scheduled_for) - Date.parse(b.scheduled_for) : Date.parse(b.scheduled_for) - Date.parse(a.scheduled_for)));
  const materials = content.filter(c => (!brand || c.brand_id === brand) && c.title.toLowerCase().includes(query.toLowerCase()));
  const next = scope.filter(active).sort((a, b) => Date.parse(a.scheduled_for) - Date.parse(b.scheduled_for))[0];
  const stats = [{ label: "Brand dikelola", value: brands.length, icon: Building2, tone: "purple" }, { label: "Konten tersimpan", value: content.filter(c => !brand || c.brand_id === brand).length, icon: FolderOpen, tone: "blue" }, { label: "Antrean aktif", value: scope.filter(active).length, icon: Clock3, tone: "amber" }, { label: "Publikasi terbit", value: scope.filter(j => j.status === "posted").length, icon: CheckCircle2, tone: "green" }];
  return <>
    {!library && <><section className="metrics">{stats.map(s => <article key={s.label}><span className={`metric-icon ${s.tone}`}><s.icon size={21}/></span><span>{s.label}</span><b>{s.value}</b></article>)}</section><section className="overview-strip"><span className="strip-icon"><CalendarDays size={24}/></span><div><small>BERIKUTNYA DALAM ANTREAN</small><h3>{next ? contentMap.get(next.content_item_id)?.title || "Konten dalam antrean" : "Siapkan publikasi pertamamu"}</h3><p>{next ? `${date(next.scheduled_for)} WIB · ${next.platform === "instagram" ? "Instagram" : "Facebook"} ${next.publish_kind}` : "Unggah bahan konten, lalu pilih channel untuk membuat jadwal."}</p></div><button className="text-button" onClick={onUpload}>Upload konten <ArrowUpRight size={17}/></button></section></>}
    <section className="card"><div className="section-heading"><div><h3>{library ? "Konten terbaru" : "Jadwal publikasi"}</h3><p>{library ? "Bahan konten yang sudah diunggah tim." : "Satu baris untuk setiap channel. Semua jadwal ditampilkan dalam WIB."}</p></div><span className="count-pill">{library ? materials.length : listed.length} item</span></div><div className="filters"><label className="search-field"><Search size={17}/><input aria-label="Cari judul konten" placeholder="Cari judul konten…" value={query} onChange={e => setQuery(e.target.value)}/></label><select aria-label="Filter brand" value={brand} onChange={e => setBrand(e.target.value)}><option value="">Semua brand</option>{brands.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</select>{!library && <select aria-label="Filter status" value={status} onChange={e => setStatus(e.target.value)}><option value="">Semua status</option><option value="active">Antrean aktif</option><option value="posted">Terbit</option><option value="failed">Gagal</option><option value="cancelled">Dibatalkan</option></select>}</div>
    {library ? materials.length ? <div className="content-grid">{materials.map(c => <article className="content-tile" key={c.id}><div className="media-placeholder">{c.media_type === "video" ? <Video size={30}/> : <FileImage size={30}/>}<span>{c.media_type === "video" ? "VIDEO" : "GAMBAR"}</span></div><div className="tile-body"><small>{brandName(c.brand_id)}</small><h4>{c.title}</h4><div><Badge status={c.status}/><time>{date(c.created_at)}</time></div></div></article>)}</div> : <Empty onUpload={onUpload}/> : listed.length ? <div className="table-wrap"><table><thead><tr><th>Konten & brand</th><th>Channel</th><th>Jadwal · WIB</th><th>Status</th></tr></thead><tbody>{listed.map(j => { const c = contentMap.get(j.content_item_id); return <tr key={j.id}><td><strong>{c?.title || `Konten ${j.content_item_id.slice(0, 8)}`}</strong><small>{brandName(c?.brand_id)}</small></td><td><span className={`platform-tag ${j.platform}`}>{j.platform === "instagram" ? "IG" : "FB"}</span> <span className="channel-kind">{j.publish_kind}</span></td><td>{date(j.scheduled_for)}</td><td><Badge status={j.status}/>{j.error_message && <details className="job-error"><summary>Detail kendala</summary><p>{j.error_message}</p></details>}</td></tr>; })}</tbody></table></div> : <Empty onUpload={onUpload}/>}
    <p className="data-scope">Data yang dimuat: hingga 100 konten terbaru dan 200 jadwal terbaru. Filter brand mengikuti konten yang dimuat. Jumlah publikasi dihitung per channel.</p></section>
  </>;
}
function Empty({ onUpload }: { onUpload: () => void }) { return <div className="empty-state"><FolderOpen size={32}/><h4>Belum ada item yang ditampilkan</h4><p>Ubah filter pencarian atau mulai dengan mengunggah konten.</p><button onClick={onUpload}><UploadCloud size={17}/>Upload konten</button></div>; }

export function MediaPicker() {
  const [file, setFile] = useState<File | null>(null), [preview, setPreview] = useState("");
  useEffect(() => { if (!file) { setPreview(""); return; } const url = URL.createObjectURL(file); setPreview(url); return () => URL.revokeObjectURL(url); }, [file]);
  return <div className="media-picker"><label className="file-drop"><UploadCloud size={30}/><strong>{file?.name || "Pilih gambar atau video"}</strong><span>JPG, PNG, WebP, MP4, atau MOV</span><input name="file" type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/quicktime" required onChange={e => setFile(e.target.files?.[0] || null)}/></label>{preview && <div className="media-preview">{file?.type.startsWith("video/") ? <video controls preload="metadata" src={preview}/> : <img src={preview} alt="Pratinjau bahan konten yang dipilih"/>}<small>{((file?.size || 0) / 1024 / 1024).toFixed(1)} MB · Pratinjau berkas asli</small></div>}</div>;
}
